repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args: [--autofix]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=auto]
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports, --allow-untyped-decorators]
        additional_dependencies: [numpy == 1.21.3]
